---
- name: Add SSH key to all hosts
  hosts: all
  become: true
  tasks:
    - name: Ensure .ssh directory exists for ansible user
      file:
        path: /home/ansible/.ssh
        state: directory
        mode: '0700'
        owner: ansible
        group: ansible

    - name: Copy SSH public key to authorized_keys
      copy:
        src: ~/.ssh/id_rsa.pub  # Chemin vers votre clé publique
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: '0600'
        remote_src: no

