---
- name: Install Java on target hosts
  hosts: REHL
  become: yes
  tasks:

    - name: Copy java zip package into the server
      ansible.builtin.copy:
        src: ../packages/jdk-23_linux-aarch64_bin.tar.gz
        dest: /home/ansible/jdk-23_linux-aarch64_bin.tar.gz
        mode: '0755'

    - name: Unpackage the Java tarball
      ansible.builtin.unarchive:
        src: /home/ansible/jdk-23_linux-aarch64_bin.tar.gz
        dest: /usr/local
        remote_src: yes

    - name: Set ownership for the Java directory
      ansible.builtin.file:
        path: /usr/local/jdk-23.0.1
        owner: root
        group: root
        recurse: yes

    - name: Create symbolic link for Java installation
      ansible.builtin.file:
        src: /usr/local/jdk-23.0.1
        dest: /usr/local/java
        state: link

    - name: Set JAVA_HOME in /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "JAVA_HOME=/usr/local/java/bin"
        create: yes

    - name: Reload environment variables
      ansible.builtin.shell: source /etc/environment
      args:
        executable: /bin/bash

