---
- name: Install Java on target hosts
  hosts: REHL
  become: yes
  tasks:

    - name: Copy java rpm package into the server
      ansible.builtin.copy:
        src: ../packages/jdk-23_linux-x64_bin.rpm
        dest: /home/ansible/jdk-23_linux-x64_bin.rpm
        mode: '0755'
    
    - name: Install Java RPM package
      ansible.builtin.dnf:
        name: /home/ansible/jdk-23_linux-x64_bin.rpm
        state: present
        disable_gpg_check: true

    - name: Reload environment variables
      ansible.builtin.shell: source /etc/environment
      args:
        executable: /bin/bash
