name: Run Ansible Playbook on Controller

on:
  push:
    branches:
      - main

jobs:
  say-hello-playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set ssh-agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook on Controller
      run: ansible-playbook -i inventory.yaml playbooks/say-hello.yaml --check --diff -v
      working-directory: ./

